apiVersion: v1
kind: Service
metadata:
  name: projectcapstone
  labels:
    app: projectcapstone
spec:
  type: LoadBalancer
  selector:
    app: projectcapstone
  ports:
    - port: 80
      targetPort: 80
